import React from 'react';
import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 9, fontFamily: 'Helvetica' },
  title: { fontSize: 16, fontWeight: 'bold', marginBottom: 8, color: '#1a1a1a' },
  subtitle: { fontSize: 10, color: '#666', marginBottom: 20 },
  table: { width: '100%' },
  header: { flexDirection: 'row', borderBottom: '1 solid #ccc', paddingBottom: 6, marginBottom: 4 },
  headerCell: { fontWeight: 'bold', fontSize: 8, color: '#444', textTransform: 'uppercase' },
  row: { flexDirection: 'row', borderBottom: '1 solid #eee', paddingVertical: 4 },
  cell: { fontSize: 9, color: '#333' },
  footer: { marginTop: 24, fontSize: 8, color: '#999', textAlign: 'center' },
});

interface Column {
  key: string;
  label: string;
  width: string;
  transform?: (val: unknown) => string;
}

export async function generateListPdf(
  title: string,
  subtitle: string,
  columns: Column[],
  data: Record<string, unknown>[]
): Promise<Buffer> {
  const doc = (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>{title}</Text>
        <Text style={styles.subtitle}>{subtitle}</Text>
        <View style={styles.table}>
          <View style={styles.header}>
            {columns.map((col, i) => (
              <Text key={i} style={[styles.headerCell, { width: col.width }]}>
                {col.label}
              </Text>
            ))}
          </View>
          {data.map((row, ri) => (
            <View key={ri} style={styles.row} wrap={false}>
              {columns.map((col, ci) => (
                <Text key={ci} style={[styles.cell, { width: col.width }]}>
                  {col.transform ? col.transform(row[col.key]) : String(row[col.key] ?? '')}
                </Text>
              ))}
            </View>
          ))}
        </View>
        <Text style={styles.footer}>Generated by StockPilot</Text>
      </Page>
    </Document>
  );

  const blob = await pdf(doc).toBlob();
  const buffer = Buffer.from(await blob.arrayBuffer());
  return buffer;
}
